[project]
name = "jutetransfer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.3",
    "streamlit>=1.53.0",
    "streamlit-aggrid>=1.2.1.post2",
    "mysql-connector-python>=9.0.0",
    "sqlalchemy>=2.0.0",
    "python-dotenv>=1.0.0",
]

[project.optional-dependencies]
dev = ["pytest>=8.0.0"]
